### ISSUE TITLE
Right click to edit is not working when playing on server

### ISSUE THREAD

**Issue by harahetaman** [RakambdaOrg/EditSign#100]
### Describe the bug

Does this mod work on Multi Play Server?
I downloaded your mod in [here](https://www.curseforge.com/minecraft/mc-mods/edit-sign/files/3564702). 
It says `2.2.7` but the name of the downloaded jar was `EditSign-1.18.2-0.0.1-dev.jar`.

Here is a video for issue reproduction:
https://user-images.githubusercontent.com/29687810/156992405-928a9897-af3c-494a-825c-837f3eee61f5.mp4

### Minecraft version

1.18.1

### Fabric API version

0.13.2

### Mod version

2.2.7

**Comment by Rakambda** [comment]
For the file name yeah it is different. Automatic upload failed so I uploaded it manually from my setup. But the file is correct.

The mod has to be installed server side for it to work (and maybe the client too, i'm not sure).

What's your "setup" in the video above? Mod is installed only client side ?

**Comment by Rakambda** [comment]
And hmmm, if you downloaded a file named `EditSign-1.18.2-0.0.1-dev.jar` then it's probably `2.3.0` and not `2.2.7` that you linked above.

**Comment by harahetaman** [comment]
Sorry my link was wrong! Anyway, I tried 2.2.7 on the link you referring and it still does not work.

According to your explanation, I think it just a specification. I installed EditSign on my side (client) and I do not own the server I play. It hosted by someone else.

 At least the 2.2.7 works fine on Single Player map, it can be worked on client side as well.

**Comment by Rakambda** [comment]
If playing on a server it has to be installed on the server as this is where the decision of what happens when you right click is taken.

**Comment by mk-pmb** [comment]
@harahetaman Could you please edit the thread title and add "… when not installed on server"? Thanks in advance!
