### ISSUE TITLE
Support mods

### ISSUE THREAD

**Issue by Romz24** [RakambdaOrg/EditSign#11]
Can you add support for third party mods? There are many mods that add plaques, but they cannot be edited.

- [BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether)

**Comment by Rakambda** [comment]
I don't reeally know what part of the mod adds "plaques" though seems like it adds a BetterNetherSign.

Not sure I can directly add support for it as it is does not provide an API for it (If I'd add support for it, my mod would depend on BN and everyone would need to have it).

The easiest would be to have the mod inherit the behavior of `SignBlockEntity`.

For example here https://github.com/paulevsGitch/BetterNether/blob/f996cccbb5985d19b57063b386ede1a1d146474e/src/main/java/paulevs/betternether/blockentities/BNSignBlockEntity.java#L32 it defines a behaviour from `BlockEntity`, so I have no way to know on my side that this is supposed to be a sign.
If instead this class inherits from the `BlockSignEntity`, all the behaviour wouldn't have to be redefined and EditSign can hook into it like if it was a normal sign (https://github.com/RakSrinaNa/EditSign/blob/9b7e7ca6dd2207e8286a179176da9672d633ed62/src/main/java/fr/raksrinana/editsign/mixin/SignBlockEntityMixin.java#L16-L23).
