### ISSUE TITLE
Dyes open the edit interface

### ISSUE THREAD

**Issue by Boobies** [RakambdaOrg/EditSign#21]
It should be contextual so that we don't always get the edit interface whenever we want to change the color of the text of our signs.

**Comment by Rakambda** [comment]
Would have been nice to follow the template provided for a reason.

I'll assume you're on Forge latest version and latest version of EditSign.

In that case I can't reproduce. Dying a sign doesn't open the text editor.

**Comment by Rakambda** [comment]
My bad, I started the Fabric version by mistake.
Can reproduce.

**Comment by Boobies** [comment]
Wait, what? I'm using version 2.2.0 on **Fabric**. You can only reproduce it on Forge?

**Comment by Rakambda** [comment]
Version 2.2.0 on Fabric 1.16.5 I can't reproduce it. Though on Forge I can.

**Comment by Boobies** [comment]
This is very surprising, as I've only used the Fabric port. I will do more extensive testing tomorrow to see whether this is caused by a conflict with any of my other mods.
