### ISSUE TITLE
FAILURE: Build failed with an exception. […] configuration of task ':forge:signJar' (type 'SignJar').

### ISSUE THREAD

**Issue by mk-pmb** [RakambdaOrg/EditSign#221]
### Describe the bug

Hi!
First of all, thanks for EditSign! It's very useful.

I was trying to build from tag `1.17.1-2.2.3` ([actions run](https://github.com/mk-pmb/ghabuild-minecraft-mod-editsign/actions/runs/4787721082/jobs/8513331492)) and it fails with [this rather long error message](https://gist.github.com/mk-pmb/e2514c25641092cd1b2a2a6c5f22bf3e).

I guess the relevant parts are these:

>   - In plugin 'net.minecraftforge.gradle' type 'net.minecraftforge.gradle.common.tasks.SignJar' property 'alias' doesn't have a configured value.
>  Possible solutions: […] 2. Mark property 'alias' as optional.
>
>   - In plugin 'net.minecraftforge.gradle' type 'net.minecraftforge.gradle.common.tasks.SignJar' property 'storePass' doesn't have a configured value.
>  Possible solutions: […] 2. Mark property 'storePass' as optional.

Is this something I should hot-patch before build?
Or maybe I have to configure something before building.
I was looking for instructions how to build, but couldn't find them in latest master's `README.*`, and there were no files `COMPIL*.*` or `BUILD*.*`.

It also says

> * Try: Run with --debug option to get more log output. Run with --scan to get full insights.

albeit the task was already invoked with `--scan`, exactly: `./gradlew build --stacktrace --info --scan`

Is signing the JAR an optional step? Is there a way to just skip it?

### Minecraft version

1.17.1 (guessing from tag name)

### Forge version

no idea

### Mod version

2.2.3 (guessing from tag name)

### Relevant log output

<details><summary>(Copy of the gist linked above)</summary>

```text
> Task :forge:build
Skipping task ':forge:build' as it has no actions.
:forge:build (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
:buildJar (Thread[Daemon worker,5,main]) started.


FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':forge:signJar' (type 'SignJar').
  - In plugin 'net.minecraftforge.gradle' type 'net.minecraftforge.gradle.common.tasks.SignJar' property 'alias' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'alias'.
      2. Mark property 'alias' as optional.
    
    Please refer to https://docs.gradle.org/7.2-rc-1/userguide/validation_problems.html#value_not_set for more details about this problem.
  - In plugin 'net.minecraftforge.gradle' type 'net.minecraftforge.gradle.common.tasks.SignJar' property 'storePass' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'storePass'.
      2. Mark property 'storePass' as optional.
    
    Please refer to https://docs.gradle.org/7.2-rc-1/userguide/validation_problems.html#value_not_set for more details about this problem.

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.
```

</details>

**Comment by Rakambda** [comment]
You may want to remove the jar signing as it requires to setup a GPG key and set env variables to function.
A way could be to use what has been used in the more recent versions of the mod:
https://github.com/Rakambda/EditSign/blob/minecraft/1.19.4/forge/build.gradle#L110-L125

**Comment by mk-pmb** [comment]
Thanks! I'll try and make a patch based on that, or find one to cherry-pick. I'll close here once I succeed.

Update: 👍  in `build.gradle`

```diff
-    finalizedBy ":forge:signJar"
+    // finalizedBy ":forge:signJar"
```
