### ISSUE TITLE
A problem occurred evaluating project ':forge'. path may not be null or empty string. path='null'

### ISSUE THREAD

**Issue by mk-pmb** [RakambdaOrg/EditSign#222]
### Describe the bug

Similar to the bug a few minutes ago, I was trying to build tag `2.2.6` ([actions run](https://github.com/mk-pmb/ghabuild-minecraft-mod-editsign/actions/runs/4787721082/jobs/8513332105)), but I probably missed some step in configuring the build.

> FAILURE: Build failed with an exception.

### Minecraft version

1.18 (from gradle config)

### Forge version

no idea

### Mod version

2.2.6 (guessing from tag name)

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/ghabuild-minecraft-mod-editsign/ghabuild-minecraft-mod-editsign/mod-repo/forge/build.gradle' line: 88

* What went wrong:
A problem occurred evaluating project ':forge'.
> path may not be null or empty string. path='null'

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':forge'.
```

**Comment by Rakambda** [comment]
I'm not too sure about this one, but may be the same as the other issue where the path to the gpg key file is missing?
https://github.com/Rakambda/EditSign/blob/2.2.6/forge/build.gradle#L88

Another idea may be the run directory (https://github.com/Rakambda/EditSign/blob/2.2.6/forge/build.gradle#L44). I'm not really a gradle expert so either you'll need to remove these overrides to have it work, or create the folder.

**Comment by mk-pmb** [comment]
Thank you again for your hints! Unfortunately I have to abandon fixing the old versions for lack of time.
