### ISSUE TITLE
Framed sign from framed block

### ISSUE THREAD

**Issue by stacode123** [RakambdaOrg/EditSign#238]
### Describe the bug

I cant edit a sign from framed blocks
[FramedBlocks-5.8.0.zip](https://github.com/Rakambda/EditSign/files/11712232/FramedBlocks-5.8.0.zip)

### Minecraft version

1.18.2

### Forge version

40.1.70

### Mod version

2.3.1

**Comment by Rakambda** [comment]
FramedBlocks does not extend the vanilla SignBlockEntity and redo everything by itself. Therefore it isn't picked up by the mod.
https://github.com/XFactHD/FramedBlocks/blob/1.20/src/main/java/xfacthd/framedblocks/common/blockentity/FramedSignBlockEntity.java#L24

It'd require to add a specific implementation for this mod which I won't do. Especially with 1.20 where it's added by default, developers will slowly move towards implementing it themself.
