### ISSUE TITLE
[Feature request] can you pls port it to fabric?

### ISSUE THREAD

**Issue by sphings79** [RakambdaOrg/EditSign#3]
Would be nice,

if you could port the 1.15.2 and 1.16.1 also to fabric 👍 

regards

sphings

**Comment by Rakambda** [comment]
Try with that release https://github.com/RakSrinaNa/EditSign/releases/tag/Fabric-1.16.1-2.0.0 and if it seems fine I'll see to release it and port it back to 1.15.

**Comment by Rakambda** [comment]
I actually released it. If there's problems with it open another issue.
