### ISSUE TITLE
Unable to add colors to signs

### ISSUE THREAD

**Issue by hsnopi** [RakambdaOrg/EditSign#38]
**Describe the bug**
I am unable to add colors to signs.

**To Reproduce**
1.  place any sign
2.  alt+0167 
3. that should allow the color codes. but no joy

**Infos:**
 - Minecraft version: [e.g. 1.16.4]
 - Mod version: [e.g. 1.16.4]
 - Forge version: [e.g. 1.16.4]

If you provide a crash report please include it in a readable way (like pastebin or gist for example).

**Comment by Rakambda** [comment]
This is how Minecraft behaves and has nothing to do with the mod. If you try with a vanilla Minecraft you'll have the same behavior.

See MC-1572
