### ISSUE TITLE
You are able to edit signs in Adventure mode

### ISSUE THREAD

**Issue by CalXee** [RakambdaOrg/EditSign#6]
**Describe the bug**
In adventure mode, you cannot grief. Editing signs could count as griefing.

**To Reproduce**
1. Go into adventure mode.
2. Try to edit a sign
Result: You can edit the sign.
Expected result: You cannot edit the sign because you are in Adventure mode.

**Infos:**
 - Minecraft verson: 1.16.2
 - Mod version: 2.0.0
 - Mod loader: Fabric 0.9.1, build 205

**Comment by Rakambda** [comment]
Will be released on Curse in a few minutes when it's approved :)
