### ISSUE TITLE
EditSign-Fabric-1.15.2-2.0.0.jar won't worl

### ISSUE THREAD

**Issue by sphings79** [RakambdaOrg/EditSign#7]
**Describe the bug**
I can't edit signs.
I'm on Fabric 0.9.0 and latest fabric Api. I've disabled all other mods. Still not working for me.

**Infos:**
 - Minecraft verson: 1.15.2
 - Mod version: EditSign-Fabric-1.15.2-2.0.0.jar
 - Moad loader: Fabric

**Comment by sphings79** [comment]
Sorry missed to write: Not working on Multiplayer.

**Comment by Rakambda** [comment]
Should be fixed in version 2.1.1
