### ISSUE TITLE
EditSign-Fabric-1.15.2-2.1.1 still won't work

### ISSUE THREAD

**Issue by sphings79** [RakambdaOrg/EditSign#8]
**Describe the bug**
EditSign-Fabric-1.15.2-2.1.1 still won't work for me on multiplayer.

**Infos:**
 - Minecraft verson: 1.15.2
 - Mod version: EditSign-Fabric-1.15.2-2.1.1
 - Moad loader: Fabric

**Comment by Rakambda** [comment]
Can't reproduce. Are you sure you're loading the mod on the server too?

**Comment by sphings79** [comment]
seems the jar was corrupted.
I've redownloaded the jar and it works fine.
