### ISSUE TITLE
Add an option to disable the vanilla sign editing or heck, just make it a default feature of this mod.

### ISSUE THREAD

**Issue by NightOps007** [RakambdaOrg/EditSign#82]
### Describe the feature

I hate having to close the sign editor every time I place signs on my farms to block liquids. It would be awesome if this mod could turn off the vanilla editing after sign placement and only allow the left click to edit the sign text that the mod adds.

**Comment by Rakambda** [comment]
I'll look a bit more into it after the holidays, but from what I saw quickly it may be doable for fabric, for forge it may require more work.

**Comment by Rakambda** [comment]
Sorry it took so long, I forgot about it 😆 

This will be for 1.19.4+ and you can test it from this build: https://github.com/Rakambda/EditSign/actions/runs/4440927412 (you'll can download it from the artifacts, the mod will be inside the zip). If it goes well I'll repease it.
