### ISSUE TITLE
Can't edit sign on server

### ISSUE THREAD

**Issue by boasbakker** [RakambdaOrg/EditSign#83]
### Describe the bug

The server also has the mod installed. 

### Minecraft version

1.18.1

### Fabric API version

0.45.0

### Mod version

2.2.7

**Comment by Rakambda** [comment]
Cannot reproduce, maybe you have another mod that is incompatible with EditSign.

https://user-images.githubusercontent.com/1688389/147492789-19dda8cb-3e25-4fd4-9ce2-f23cf661a32c.mp4

**Comment by boasbakker** [comment]
The server has these mods:
        - alternatecurrent 1.1.0
        - antixray 1.1.1
        - c2me 0.2.0+alpha.5.106
        - carpet 1.4.56
        - carpet-extra 1.4.56
        - carpet-tis-addition 1.27.3
        - cloth-basic-math 0.6.0 via cloth-config
        - cloth-config 6.1.48 via editsign
        - com_electronwill_night-config_core 3.6.4 via servercore-fabric
        - com_electronwill_night-config_toml 3.6.4 via servercore-fabric
        - com_moandjiezana_toml_toml4j 0.7.2 via antixray
        - editsign 2.2.7
        - elativitymc_c2me-fabric_ver_1_18_libs_ 0.2.0+alpha.5.106 via c2me
        - fabric 0.45.0+1.18
        - fabric-api-base 0.4.1+b4f4f6cd65 via fabric
        - fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
        - fabric-biome-api-v1 6.0.1+ded849a965 via fabric
        - fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
        - fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
        - fabric-containers-v0 0.1.18+d154e2c665 via fabric
        - fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
        - fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
        - fabric-dimensions-v1 2.1.7+43d2957165 via fabric
        - fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
        - fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
        - fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
        - fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
        - fabric-item-api-v1 1.3.0+691a79b565 via fabric
        - fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
        - fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
        - fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
        - fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
        - fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
        - fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
        - fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
        - fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
        - fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
        - fabric-particles-v1 0.2.9+526dc1ac65 via fabric
        - fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
        - fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
        - fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
        - fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
        - fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
        - fabric-structure-api-v1 2.0.8+295197a765 via fabric
        - fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
        - fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
        - fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
        - fabricloader 0.12.12
        - ferritecore 4.0.0
        - java 17
        - ksyxis 1.1
        - lazydfu 0.1.2
        - lithium 0.7.6
        - minecraft 1.18.1
        - org_yaml_snakeyaml 1.29 via carpet-tis-addition
        - perfectaccuracy 1.2
        - rotb 0.1
        - servercore-fabric 1.2.6-1.18.1
        - servertick 1.6
        - servux 0.1.0
        - starlight 1.0.0+fabric.d0a3220
        - vmp 0.2.0+beta.2.0
        - worldedit 7.2.8+6008-1246d61

**Comment by boasbakker** [comment]
Okay, the problem is the client, not the server. So these are my client mods:
251 mods:
	- advanced_runtime_resource_pack 0.5.1 via extrasounds
	- advancementinfo 1.18-fabric0.43.1-1.3
	- afkpeace 4.6.5
	- alternatecurrent 1.1.0
	- amecsapi 1.3.3+mc1.18-pre1 via dontdropit
	- antighost 1.18-fabric0.43.1-1.1.4
	- anvil-crush 1.6.0
	- anvil_crushing_recipes 1.3.2-b1+MC1.18-1.18.1
	- architectury 3.2.51
	- authme 2.2.0
	- autoconfig1u 3.3.1
	- beenfo 1.18-fabric0.43.1-1.3.3
	- betterbeds 1.2.0
	- betterbiomeblend 1.17.0-1.1.4-fabric
	- betterdroppeditems 1.3.1-21w37a
	- betterpingdisplay 1.1
	- betterrecipebook 1.5.5
	- blur 2.4.1
	- bobby 3.1.0
	- brandpacket 0.0.2.1
	- carpet 1.4.56
	- carpet-extra 1.4.56
	- carpet-tctc-addition 1.1.6+d3d2466
	- carpet-tis-addition 1.27.3
	- ccoords 0.1.2149b
	- chunkpregen 0.3.3
	- chunky 1.2.153
	- citresewn 0.8.1-1.18
	- clean-debug 1.0.1
	- clean-logs 1.0.1
	- clear-skies 2.0.88
	- cleardespawn 1.1.5
	- clickthrough 1.18-fabric0.43.1-0.4
	- clientarguments b1.1.4 via seedmapper
	- cloth-api 2.0.54
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 2.0.54 via cloth-api
	- cloth-common-events-v1 2.0.54 via cloth-api
	- cloth-config 6.1.48
	- cloth-config-lite 2.0.6 via petowner
	- cloth-datagen-api-v1 2.0.54 via cloth-api
	- cloth-scissors-api-v1 2.0.54 via cloth-api
	- cloth-utils-v1 2.0.54 via cloth-api
	- com_moandjiezana_toml_toml4j 0.7.2 via clean-logs
	- com_typesafe_config 1.4.1 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- confabricate 2.1.0-SNAPSHOT+4.1.1 via bobby
	- continuity 1.0.0+1.17
	- convenient-mobgriefing 2.0.2
	- creativeonepunch 1.3
	- crowdin-translate 1.4+1.18 via antighost
	- customsplashscreen 1.2.0
	- deathlog 0.2.2+1.18
	- dontdropit 2.3.6+1.18
	- draggable-resource-packs 1.0.1
	- dual_riders 1.0.5
	- durabilityviewer 1.18-fabric0.43.1-1.10.2
	- dynamic-surroundings 1.1
	- dynamicfps 2.0.6
	- easiercrafting 1.18-fabric0.43.1-1.7
	- easiervillagertrading 1.18-fabric0.43.1-1.5.4
	- eatinganimationid 1.2
	- eggtab 2.1.0+1.16-fabric
	- enchlevel-langpatch 0.2.0
	- entityoutliner 1.2.0
	- environmentalcreepers 1.6.0
	- extrasounds 2.1.1+1.18
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via bobby
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d95c8 via bobby
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via invview
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via citresewn
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fabricskyboxes 0.5.4
	- fabrilousupdater 2.5+1.18.1
	- fabrishot 1.6.0
	- fallingleaves 1.8.1+1.18.1
	- ferritecore 4.0.0
	- flytre-lib-base 1.3.0 via flytre_lib
	- flytre-lib-compat 1.0.0 via flytre_lib
	- flytre-lib-config 1.1.0 via flytre_lib
	- flytre-lib-event 1.0.1 via flytre_lib
	- flytre-lib-gui 1.0.0 via flytre_lib
	- flytre-lib-storage 2.3.2 via flytre_lib
	- flytre_lib 1.4.4
	- food_highlight 1.0.3
	- fvt 1.9.0-mc1.18.1
	- gbfabrictools 1.3.4+1.18 via beenfo
	- grabcraft-downloader 1.18-fabric0.43.1-0.5
	- grass_pass 1.1.0
	- here-be-no-dragons 1.0.0
	- hudtweaks 1.2.1-beta
	- hudtweaks-apihelper 1.0-beta via hudtweaks
	- indium 1.0.2-alpha1+mc1.18
	- inspecio 1.1.0+1.17
	- invmove 1.18-0.1.0
	- invview 1.4.8-1.18+
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- iris 1.1.3
	- isometric-renders 0.2.7-21w39a
	- itemscroller 0.15.0
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- keepheadnames 1.4-1.18
	- kirin 1.10.0-beta.2 via presencefootsteps
	- krypton 0.1.6
	- ksrch 1.0.0
	- ksyxis 1.1
	- lambdabettergrass 1.2.1+1.17
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- libjf-base 2.2.0 via slyde
	- libjf-config-v0 2.2.0 via slyde
	- libjf-unsafe-v0 2.2.0 via slyde
	- libzoomer 0.3.0+1.17.1 via okzoomer
	- lightoverlay 6.0.0
	- litematica 0.9.0
	- lithium 0.7.6
	- loading-timer 1.5
	- magiclib 1.0.0+build.undefined via tweakmyclient
	- malilib 0.10.0-dev.26
	- masa_gadget_mod 21w41a-2.0.6
	- mcwifipnp 1.5.3
	- memoryusagescreen 1.2
	- midnightlib 0.3.1 via blur
	- minecraft 1.18.1
	- minihud 0.19.0-dev.20211204.230657
	- mixintrace 1.1.0+1.17
	- mm 2.1 via slight-gui-modifications
	- modmanager 1.2.1+1.18
	- modmenu 3.0.1
	- moretags 1.4.8
	- multiconnect-api 1.4.16 via pca
	- name_lookup 1.0.2
	- nethermap 1.5.0-1.18
	- nmuk 1.0.1+mc1.18-pre1
	- no_nether_portal_overlay 1.0.2
	- noanglebrackets 1.1.0
	- notenoughcrashes 4.1.3+1.18
	- offlineskins 1.17.1-v2-fabric
	- okzoomer 5.0.0-beta.3+1.17.1
	- ommc 21w41a-0.3.9-beta.df860a9
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_codehaus_groovy_groovy 3.0.8 via slight-gui-modifications
	- org_codehaus_groovy_groovy-jsr223 3.0.8 via slight-gui-modifications
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- org_slf4j_slf4j-api 1.7.12 via iris
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- org_yaml_snakeyaml 1.29 via carpet-tis-addition
	- pca 0.2.2
	- pehkui 3.0.0+1.14.4-1.18
	- perfectaccuracy 1.2
	- petowner 1.8.2-1.18-pre4+
	- pickblockpro 1.5.4-beta
	- pinglist 1.3.2
	- presencefootsteps 1.4.0
	- pride 1.1.0+1.17 via lambdynlights
	- quickconnectbutton 1.0
	- reeses-sodium-options 1.2.3
	- replanter 1.3
	- rotb 0.1
	- satin 1.7.0 via blur
	- seedmapper b1.4.6
	- servertick 1.6
	- sgui 1.0.0-rc6+1.18-pre5 via invview
	- silence 1.18-fabric0.43.1-1.0.1
	- slight-gui-modifications 2.0.2
	- slyde 1.5.0
	- sodium 0.4.0-alpha5+build.9
	- sodium-extra 0.3.7
	- soundcategories 1.1.0+1.18 via extrasounds
	- spark 1.6.3
	- spruceui 3.3.0+1.17 via lambdabettergrass
	- starlight 1.0.0+fabric.d0a3220
	- statssearch 1.18-fabric0.43.1-1.0.1
	- stepup 1.18-fabric0.43.1-1.1
	- tiefix 1.8.0
	- timechanger 1.0.0
	- tputils 1.5.11-beta
	- tweakeroo 0.11.0
	- tweakmyclient 1.1.11+bba69f9
	- viabackwards 4.1.1
	- viafabric 0.4.5+244-main
	- viafabric-mc118 0.4.5+244-main via viafabric
	- viarewind 2.0.2-SNAPSHOT
	- viaversion 4.1.1-SNAPSHOT via viafabric
	- visualoverhaul 4.0.0
	- vmp 0.2.0+beta.2.0
	- voicechat 1.18.1-2.1.28
	- worldedit 7.2.8+6008-1246d61
	- worldmesher 0.1-21w39a via isometric-renders
	- wthit 4.3.1
	- wthit-plugins 1.0.0
	- xaerominimap 21.22.6
	- xaeroworldmap 1.18.9

**Comment by Rakambda** [comment]
Well, I won't go through all mods download them 1 by 1 to test until finding which one is incompatible (especially that there's quite a lot of them).

If you want to you can do so. The fastest is to remove half of the mods each time, so restarting the client 8 times should be enough to narrow it down to EditSign + the other mod.
