### ISSUE TITLE
Cannot edit while on the wall

### ISSUE THREAD

**Issue by AdminHcat** [RakambdaOrg/EditSign#89]
### Describe the bug

Cannot edit while on the wall

### Minecraft version

1.18.1

### Fabric API version

0.44.0

### Mod version

2.2.7

**Comment by Rakambda** [comment]
I cannot reproduce.

https://user-images.githubusercontent.com/1688389/149396997-79cca028-59cd-4d01-8708-8b4253a82f82.mp4

**Comment by luckydonald** [comment]
Having the same problem on my server.

**Comment by Rakambda** [comment]
To be clear, when a "wall" is mentioned, is it :

1 - The wall block
2 - Against a block (not standing on a "pole")

-----

Does it work if not on a wall ?

----

Do you have other mods installed ?
